
export const OPERATION_PROCESSING = 'OPERATION_PROCESSING'; 
export const OPERATION_COMPLETED = 'OPERATION_COMPLETED';
export const OPERATION_FAILED = 'OPERATION_FAILED'; 
export const OPERATION_SUCCEEDED = 'OPERATION_SUCCEEDED'; 
export const OPERATION_CLEARED = 'OPERATION_CLEARED'; 

export const UPDATE_ITEM_IN_REDUX = 'UPDATE_ITEM_IN_REDUX'; 
export const REMOVE_ITEM_FROM_REDUX = 'REMOVE_ITEM_FROM_REDUX';
export const REPLACE_ITEM_IN_REDUX = 'REPLACE_ITEM_IN_REDUX'; 

export const AFTER_PERSIST = 'AFTER_PERSIST'
