
export const OPERATION_PROCESSING = 'OPERATION_PROCESSING'; 
export const OPERATION_COMPLETED = 'OPERATION_COMPLETED';
export const OPERATION_FAILED = 'OPERATION_FAILED'; 
export const OPERATION_SUCCEEDED = 'OPERATION_SUCCEEDED'; 
export const OPERATION_CLEARED = 'OPERATION_CLEARED'; 