
export const OPERATION_PROCESSING = 'OPERATION_PROCESSING'; 
export const OPERATION_COMPLETED = 'OPERATION_COMPLETED';
export const OPERATION_FAILED = 'OPERATION_FAILED'; 
export const OPERATION_SUCCEEDED = 'OPERATION_SUCCEEDED'; 
export const OPERATION_CLEARED = 'OPERATION_CLEARED'; 

export const UPDATE_ITEM_IN_REDUX = 'UPDATE_ITEM_IN_REDUX'; 
export const REMOVE_ITEM_FROM_REDUX = 'REMOVE_ITEM_FROM_REDUX';
export const REPLACE_ITEMS_IN_REDUX = 'REPLACE_ITEMS_IN_REDUX'; 
export const CLEAR_REDUX = 'CLEAR_REDUX'; 

export const AFTER_PERSIST = 'AFTER_PERSIST'

export const LOAD_AUTH_DATA = 'LOAD_AUTH_DATA'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SKIP_SECURITY_SETUP = 'SKIP_SECURITY_SETUP'

export const PIN_SETUP_STARTED = 'PIN_SETUP_STARTED'
export const PIN_SETUP_PASSWORD_VERIFIED = 'PIN_SETUP_PASSWORD_VERIFIED'
export const PIN_SETUP_PASSWORD_FAILED = 'PIN_SETUP_PASSWORD_FAILED'
export const PIN_SETUP_FAILED = 'PIN_SETUP_FAILED'
export const PIN_SETUP_COMPLETE = 'PIN_SETUP_COMPLETE'