
export const OPERATION_START = 'OPERATION_START';
export const OPERATION_FAIL = 'OPERATION_FAIL';
export const OPERATION_SUCCEED = 'OPERATION_SUCCEED';
export const OPERATION_CLEAR = 'OPERATION_CLEAR';

export const REPLACE_ITEMS_IN_REDUX_STORE = 'REPLACE_ITEMS_IN_REDUX_STORE';
export const CLEAR_REDUX_STORE = 'CLEAR_REDUX_STORE';

export const LOADED_AUTH_DATA = 'LOADED_AUTH_DATA';
export const SIGN_IN = 'SIGN_IN';

export const PIN_SETUP_STARTED = 'PIN_SETUP_STARTED';
export const PIN_SETUP_PASSWORD_VERIFIED = 'PIN_SETUP_PASSWORD_VERIFIED';
export const PIN_SETUP_PASSWORD_FAILED = 'PIN_SETUP_PASSWORD_FAILED';
export const PIN_SETUP_FAILED = 'PIN_SETUP_FAILED';
export const PIN_SETUP_COMPLETE = 'PIN_SETUP_COMPLETE';

export const BACKUP_STARTED = 'BACKUP_STARTED';
export const BACKUP_DATA_READY = 'BACKUP_DATA_READY';
export const BACKUP_DATA_FAILED = 'BACKUP_DATA_FAILED';
export const BACKUP_COMPLETE = 'BACKUP_COMPLETE';

export const RESTORE_STARTED = 'RESTORE_STARTED';
export const RESTORE_PASSWORD_VERIFIED = 'RESTORE_PASSWORD_VERIFIED';
export const RESTORE_FILE_PASSWORD_VERIFIED = 'RESTORE_FILE_PASSWORD_VERIFIED'; /* exported file can have password different from app */
export const RESTORE_PASSWORD_FAILED = 'RESTORE_PASSWORD_FAILED';
export const RESTORE_FILE_PASSWORD_FAILED = 'RESTORE_FILE_PASSWORD_FAILED'; /* exported file can have password different from app */
export const RESTORE_COMPLETE = 'RESTORE_COMPLETE';

export const CHANGEPASSWORD_STARTED = 'CHANGEPASSWORD_STARTED';
export const CHANGEPASSWORD_CREDENTIALS_VERIFIED = 'CHANGEPASSWORD_CREDENTIALS_VERIFIED';
export const CHANGEPASSWORD_CREDENTIALS_FAILED = 'CHANGEPASSWORD_CREDENTIALS_FAILED';
export const CHANGEPASSWORD_COMPLETE = 'CHANGEPASSWORD_COMPLETE';

export const SETTINGS_CHANGED = 'SETTINGS_CHANGED';